version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/vscode/qodana"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
